{% set name = "mlforecast" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: 07c48e7b113df14c634d2cc91c070cda36f04323f5889070cb36fcd4e6188223

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - numba
    - pandas
    - python
    - scikit-learn
    - window-ops

test:
  imports:
    - mlforecast

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting

extra:
  recipe-maintainers:
    - jmoralez
