{% set name = "mlforecast" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mlforecast-{{ version }}.tar.gz
  sha256: c65acff268b62f49bc2826a93fc4bc8615f2569c7ba35d02354cc79b7ea313f4

build:
  number: 0
  skip: true  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numba
    - pandas
    - scikit-learn
    - utilsforecast >=0.0.6
    - window-ops

test:
  imports:
    - mlforecast 
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Nixtla/mlforecast
  dev_url: https://github.com/Nixtla/mlforecast
  doc_url: https://nixtla.github.io/mlforecast/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Scalable machine learning based time series forecasting
  description: |
    mlforecast is a framework to perform time series forecasting using machine learning models, 
    with the option to scale to massive amounts of data using remote clusters.

extra:
  recipe-maintainers:
    - jmoralez
